# Generated by Django 4.0.3 on 2022-04-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(choices=[('Acer', 'Acer'), ('Macbook', 'Macbook'), ('HP', 'HP'), ('ASUS', 'ASUS'), ('Dell', 'Dell'), ('LG', 'LG'), ('Compaq', 'Compaq'), ('Lenovo', 'Lenovo'), ('Toshiba', 'Toshiba'), ('MSI', 'MSI')], max_length=100)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
