# Generated by Django 4.0.3 on 2022-04-09 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_static',
            name='location',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_static',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='sale_static',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
