# Generated by Django 4.0.3 on 2022-04-11 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(choices=[('shop rent', 'shop rent'), ('Accessories', 'Accessories')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(choices=[('Windows', 'Windows'), ('Upgrade', 'Upgrade'), ('Accessories', 'Accessories'), ('Battery', 'Battery')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='sale_static',
            name='location',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_static',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='sale_static',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
