# Generated by Django 4.0.3 on 2022-04-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_expenses_income_sale_static_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='day',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='expenses',
            name='month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='expenses',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='income',
            name='day',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='income',
            name='month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='income',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='sale_static',
            name='day',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='sale_static',
            name='month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='sale_static',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
